app.message: Hola mundo de Spring Cloud Gateway
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

spring:
  cloud:
    gateway:
      routes:
        # Microservicio clientes
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers-service/**
